localhost:8080/api/v1/auth/login/social
Content-Type: application/json
{
    "socialType": "APPLE",
    "access_token": "eyJraWQiOiJUOHRJSjF6U3JPIiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJodHRwczovL2FwcGxlaWQuYXBwbGUuY29tIiwiYXVkIjoiY29tLjlvb3JtdGhvblVOSVYuVU5JVi0tNGN1dCIsImV4cCI6MTcyOTA5MTg4MCwiaWF0IjoxNzI5MDA1NDgwLCJzdWIiOiIwMDA2NzAuMTFkOGI5Yjk1ZmU0NDQ0MTlhM2FhZGMwODY2MjdkMTMuMDM0OCIsImNfaGFzaCI6ImZHa0NpbmpYMDkydmxCdV9TSF9aT0EiLCJlbWFpbCI6IjRkNnkyNW5tYnFAcHJpdmF0ZXJlbGF5LmFwcGxlaWQuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImlzX3ByaXZhdGVfZW1haWwiOnRydWUsImF1dGhfdGltZSI6MTcyOTAwNTQ4MCwibm9uY2Vfc3VwcG9ydGVkIjp0cnVlfQ.Ar9xgehjgBVGhJ08unqsv-TlURz-M8x-C6sFrv0KJdmbuA2_AkFy_6at9s9igAhPOMFDuHZGlp3daXJrYqV9D_5WBYpgIAr98tPoQKA6OKZQzrqEjvQZmGcUmlSyCnOZTNn9MEac_XYvkXoifMMII1IQr5myBEA-IVHu3xiDPy24IVrUwKs9Z7K-vU4ECkjXvkHCTOmGQpCbY0GBe0ZLctE9LLeIHBclGF69y5EcnBKQHPywWtLspt9NPSfaN13eH7t2dSh42SuMKCAsKW5jOWZ8dHpCFNJLqXUuncSP0nQdUjmNllOAz6U8aa0oNy-Eam_rD2B4YWlRf8sJyaluhQ"
}